import { writeFileSync } from 'node:fs';
import { mechanicsData } from '../../packages/core/src/mechanics.ts';
import { publicCardById } from '../../packages/core/src/public-data.ts';
import { calculateCardProgression, cardBelongsToCharacterGrouping } from '../../packages/core/src/formation-evaluator.ts';
import { songContextData } from '../../packages/core/src/song-contexts.ts';
import benchmark from '../../data/native/ranking-benchmark-v1.json' with {type:'json'};
const cards0=[...mechanicsData.cards].sort((a,b)=>a.cardId.localeCompare(b.cardId)); const groups=new Set();
for(const c of cards0) for(const s of [...c.skills.active,...c.skills.passive,...c.skills.special,{applications:c.leaderOutfit.applications}]) for(const a of s.applications){if(a.target?.characterGroupingId)groups.add(a.target.characterGroupingId);if(a.trigger?.characterGroupingId)groups.add(a.trigger.characterGroupingId)}
const groupList=[...groups].sort(),gi=new Map(groupList.map((g,i)=>[g,i]));
const K={'score-up':1,'score-support':2,'activation-rate-up':3,'performance-up':4,'technique-up':5,'sense-up':6,'all-parameters-up':7,'active-skill-effect-up':8,'life-recovery':9,'judgement-enhance':10},T={all:1,self:2,attribute:3,'character-group':4},R={'combo-at-least':1,'deck-attribute-count':2,'deck-character-group-count':3,'life-at-least':4},C={base:0,'conditional-base':1,'conditional-override':2,additive:3,'conditional-additive':4};
const attr=x=>x==='cute'?0:x==='pure'?1:2; const bit=x=>x?1<<gi.get(x):0;
const op=a=>({c:C[a.combination],k:a.effect?K[a.effect.kind]:0,v:a.effect?.value??0,t:a.target?T[a.target.kind]:0,a:a.target?.attribute==null?-1:attr(a.target.attribute),g:bit(a.target?.characterGroupingId),n:a.target?.count??0,r:a.trigger?(R[a.trigger.kind]??0):0,q:a.trigger?.threshold??0,ra:a.trigger?.attribute==null?-1:attr(a.trigger.attribute),rg:bit(a.trigger?.characterGroupingId)});
const pick=(xs,n)=>xs.find(x=>x.level===n); const pm=id=>{let m=publicCardById.get(id),c=mechanicsData.cards.find(x=>x.cardId===id),p=calculateCardProgression(m,c,'one-copy-maximum'),a=pick(c.skills.active,p.state.activeSkillLevel),s=pick(c.skills.special,p.state.specialSkillLevel),pa=pick(c.skills.passive,p.state.passiveSkillLevel);return {id,talent:c.talentId,rarity:c.rarity,attr:attr(m.attribute),groups:[...gi].reduce((v,[g,i])=>cardBelongsToCharacterGrouping(m,g)?v|1<<i:v,0),p:[p.parameters.performance,p.parameters.technique,p.parameters.sense],passive:pa.applications.map(op),active:a.applications.map(op),special:s.applications.map(op),cooldown:a.cooldownMilliseconds,duration:a.durationMilliseconds,probability:a.activationProbabilityPermil,specialDuration:s.durationMilliseconds}};
const cards=cards0.map(c=>pm(c.cardId)); const songs=new Map(songContextData.songs.map(s=>[s.id,s])); const chartMap=new Map(songContextData.charts.map(c=>[c.key,c]));
const charts=[...benchmark.corpus.reference,...benchmark.corpus.current].map(e=>{let c=chartMap.get(e.chartKey),s=songs.get(c.songId);return {key:c.key,noteCount:c.fullComboNoteCount,duration:s.playingMilliseconds,singers:s.singerTalentIds}}); const talents=[...new Set(cards.map(c=>c.talent))].sort();
const leaders=cards.map(c=>({id:c.id,talent:c.talent,attr:c.attr,groups:c.groups,applications:mechanicsData.cards.find(x=>x.cardId===c.id).leaderOutfit.applications.map(op)})); writeFileSync(new URL('./kernel.json',import.meta.url),JSON.stringify({schemaVersion:1,methodologyVersion:'yd-exact-global-kernel-prototype-0.1.0',certificateEligible:false,source:{rosterCommit:benchmark.sources.roster.commit,benchmarkId:benchmark.benchmarkId},talents,groups:groupList,cards,leaders,charts})); console.log(`wrote ${cards.length} cards, ${talents.length} talents, ${charts.length} charts`);
