use serde::Deserialize;
use std::{cmp::Ordering,env,fs};
#[derive(Clone,Deserialize)]struct Kernel{cards:Vec<Card>,leaders:Vec<Leader>,charts:Vec<Chart>}
#[derive(Clone,Deserialize)]struct Card{id:String,talent:String,rarity:u8,attr:u8,groups:u32,p:[f64;3],passive:Vec<Op>,active:Vec<Op>,special:Vec<Op>,cooldown:f64,duration:f64,probability:f64,#[serde(rename="specialDuration")]special_duration:f64}
#[derive(Clone,Deserialize)]struct Leader{id:String,applications:Vec<Op>}
#[derive(Clone,Deserialize)]struct Chart{noteCount:usize,duration:f64}
#[derive(Clone,Deserialize)]struct Op{c:u8,k:u8,v:f64,t:u8,a:i8,g:u32,n:u8,r:u8,q:f64,ra:i8,rg:u32}
const SCORE:u8=1;const SUPPORT:u8=2;const ACTIVATION:u8=3;const PERF:u8=4;const TECH:u8=5;const SENSE:u8=6;const ALL:u8=7;const ACTIVE_SUPPORT:u8=8;
#[derive(Clone,Copy)]struct Ctx{ids:[usize;5],attrs:[u8;3],base:f64}
fn trig(o:&Op,x:&Ctx,c:&[Card],combo:Option<usize>)->bool{match o.r{0=>true,1=>combo.map(|n|n as f64>=o.q).unwrap_or(false),2=>o.ra>=0&&x.attrs[o.ra as usize]as f64>=o.q,3=>(0..5).filter(|i|c[x.ids[*i]].groups&o.rg!=0).count()as f64>=o.q,4=>1000.>=o.q,_=>false}}
fn elig(o:&Op,i:usize,x:&Ctx,c:&[Card])->bool{match o.t{1=>true,3=>o.a>=0&&c[x.ids[i]].attr==o.a as u8,4=>c[x.ids[i]].groups&o.g!=0,_=>false}}
fn pv(c:&Card,k:u8)->f64{match k{PERF=>c.p[0],TECH=>c.p[1],SENSE=>c.p[2],ALL=>c.p.iter().sum(),_=>0.}}
fn minp(o:&Op,src:Option<usize>,x:&Ctx,c:&[Card])->f64{if o.t==2{return src.map(|i|pv(&c[x.ids[i]],o.k)).unwrap_or(0.)}let mut v:Vec<f64>=(0..5).filter(|&i|elig(o,i,x,c)).map(|i|pv(&c[x.ids[i]],o.k)).collect();if v.is_empty(){return 0.}let n=if o.n==0{v.len()}else{(o.n as usize).min(v.len())};v.sort_by(|a,b|a.partial_cmp(b).unwrap_or(Ordering::Equal));v.into_iter().take(n).sum()}
fn floor(o:&Op,src:Option<usize>,x:&Ctx,c:&[Card],i:usize)->f64{if o.t==2{return if src==Some(i){1.}else{0.}}if !elig(o,i,x,c){return 0.}if o.t==1{return 1.}let e=(0..5).filter(|&j|elig(o,j,x,c)).count();let n=if o.n==0{e}else{(o.n as usize).min(e)};if e<=n{1.}else{0.}}
fn memb(x:&Ctx,c:&[Card])->(f64,[f64;5]){let(mut p,mut s)=(0.,[0.;5]);for si in 0..5{for o in c[x.ids[si]].passive.iter().filter(|o|trig(o,x,c,Some(usize::MAX))){if matches!(o.k,PERF|TECH|SENSE|ALL){p+=minp(o,Some(si),x,c)*o.v/1000.}if o.k==ACTIVE_SUPPORT{for i in 0..5{s[i]+=o.v*floor(o,Some(si),x,c,i)}}}}(p,s)}
fn lead(l:&Leader,x:&Ctx,c:&[Card])->(f64,[f64;5]){let(mut p,mut s)=(0.,[0.;5]);for o in l.applications.iter().filter(|o|trig(o,x,c,Some(usize::MAX))){if matches!(o.k,PERF|TECH|SENSE|ALL){p+=minp(o,None,x,c)*o.v/1000.}if o.k==ACTIVE_SUPPORT{for i in 0..5{s[i]+=o.v*floor(o,None,x,c,i)}}}(p,s)}
fn specials(card:&Card,x:&Ctx,c:&[Card])->(f64,f64){let(mut s,mut a)=(0.,0.);for o in &card.special{if o.r==1||!trig(o,x,c,Some(usize::MAX)){continue}if o.k==SUPPORT{s+=o.v}if o.k==ACTIVATION{a+=o.v}}(s,a)}
fn active(card:&Card,x:&Ctx,c:&[Card],combo:usize)->f64{let(mut sum,mut over)=(0.,None);for o in &card.active{if o.k!=SCORE||!trig(o,x,c,Some(combo)){continue}if o.c==2{over=Some(o.v)}else{sum+=o.v}}over.unwrap_or(sum)}
fn prob(n:usize,b:f64,a:f64)->f64{if n==0{return 0.}let p=((b+a).max(0.)).min(1000.)/1000.;1.-(1.-p).powi(n as i32)}
fn emax(v:&mut[(f64,f64);5])->f64{v.sort_by(|a,b|b.0.partial_cmp(&a.0).unwrap_or(Ordering::Equal));let(mut z,mut nh)=(0.,1.);let mut i=0;while i<5{if v[i].0<=0.||v[i].1<=0.{i+=1;continue}let q=v[i].0;let(mut j,mut ng)=(i,1.);while j<5&&(v[j].0-q).abs()<1e-9{ng*=1.-v[j].1;j+=1}z+=q*nh*(1.-ng);nh*=ng;i=j}z}
fn score(x:&Ctx,l:&Leader,ch:&Chart,c:&[Card],mp:f64,ms:&[f64;5],ss:f64,sa:f64)->f64{let(lp,ls)=lead(l,x,c);let mut total=0.;for n in 0..ch.noteCount{let at=(n as f64+0.5)*ch.duration/ch.noteCount as f64;let mut v=[(0.,0.);5];for i in 0..5{let q=&c[x.ids[i]];let last=(at/q.cooldown).floor()as i64;let first=(((at-q.duration)/q.cooldown).floor()as i64+1).max(1);let checks=if last>=first{(last-first+1)as usize}else{0};v[i]=(active(q,x,c,n+1)*(1000.+ms[i]+ls[i]+ss)/1000.,prob(checks,q.probability,sa))}total+=emax(&mut v)}((x.base+lp+mp+(total/ch.noteCount as f64)*x.base/1000.)*1_000_000.).round()/1_000_000.}
fn ctx(ids:[usize;5],c:&[Card])->Ctx{let(mut a,mut b)=([0;3],0.);for &i in &ids{a[c[i].attr as usize]+=1;b+=c[i].p.iter().sum::<f64>()}Ctx{ids,attrs:a,base:b}}
#[derive(Clone)]struct Win{score:f64,l:usize,ids:[usize;5],count:u64}
fn better(a:&Win,b:&Win,k:&Kernel)->bool{if a.score>b.score+1e-9{return true}if(a.score-b.score).abs()<1e-9{return format!("{}",k.leaders[a.l].id)<format!("{}",k.leaders[b.l].id)}false}
fn rec(k:&Kernel,g:&[Vec<usize>],i:usize,n:usize,stars:usize,ids:&mut Vec<usize>,best:&mut Win,limit:usize){if n==0{best.count+=1;let mut t=[0;5];t.copy_from_slice(ids);t.sort_unstable();let x=ctx(t,&k.cards);let(mp,ms)=memb(&x,&k.cards);let(mut ss,mut sa)=(0.,0.);for &id in &x.ids{let(s,a)=specials(&k.cards[id],&x,&k.cards);for ch in k.charts.iter().take(limit){ss+=s*k.cards[id].special_duration/ch.duration/limit as f64;sa+=a*k.cards[id].special_duration/ch.duration/limit as f64}}let(mut bs,mut bl)=(f64::NEG_INFINITY,0);for(li,l)in k.leaders.iter().enumerate(){let mut z=0.;for ch in k.charts.iter().take(limit){z+=score(&x,l,ch,&k.cards,mp,&ms,ss,sa)}z/=limit as f64;if z>bs{bs=z;bl=li}}let w=Win{score:bs,l:bl,ids:t,count:best.count};if best.score.is_infinite()||better(&w,best,k){*best=w}return}if i>=g.len()||g.len()-i<n{return}rec(k,g,i+1,n,stars,ids,best,limit);for &id in &g[i]{let s=stars+(k.cards[id].rarity==5)as usize;if s<=5{ids.push(id);rec(k,g,i+1,n-1,s,ids,best,limit);ids.pop();}}}
fn main(){let path=env::args().nth(1).unwrap_or("tools/exact-global-solver/kernel.json".into());let mut k:Kernel=serde_json::from_str(&fs::read_to_string(path).unwrap()).unwrap();let mut seen=std::collections::HashSet::new();k.leaders.retain(|l|{let key=l.applications.iter().map(|o|format!("{}:{}:{}:{}:{}:{}:{}:{}:{}:{}:{}",o.c,o.k,o.v,o.t,o.a,o.g,o.n,o.r,o.q,o.ra,o.rg)).collect::<Vec<_>>().join("|");seen.insert(key)});let limit:usize=env::var("YD_CHART_LIMIT").ok().and_then(|x|x.parse().ok()).unwrap_or(k.charts.len());let mut m=std::collections::HashMap::<String,Vec<usize>>::new();for(i,c)in k.cards.iter().enumerate(){m.entry(c.talent.clone()).or_default().push(i)}let mut g:Vec<Vec<usize>>=m.into_values().collect();g.sort_by_key(|x|x[0]);let(mut ids,mut best)=(Vec::new(),Win{score:f64::NEG_INFINITY,l:0,ids:[0;5],count:0});rec(&k,&g,0,5,0,&mut ids,&mut best,limit);println!("{{\"kind\":\"exact-global-search-prototype\",\"certificateEligible\":false,\"charts\":{},\"leaderClasses\":{},\"bestCentralUtility\":{:.6},\"leaderCardId\":\"{}\",\"memberCardIds\":[{}],\"legalTeamSetsEnumerated\":{}}}",limit,k.leaders.len(),best.score,k.leaders[best.l].id,best.ids.iter().map(|i|format!("\"{}\"",k.cards[*i].id)).collect::<Vec<_>>().join(","),best.count)}
